
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author swlab
 */
public class Consumer_entry extends javax.swing.JFrame {

    /**
     * Creates new form Consumer_entry
     */
     ksebdb cons = new ksebdb();
     Statement consstmt;
     ResultSet consrst; 
    DefaultTableModel model = new DefaultTableModel();
    public Consumer_entry() {
        initComponents();
        model.addColumn("consumer_no");
        model.addColumn("consumer_name");
        model.addColumn("telephone"); 
        model.addColumn("transformer_no");
        model.addColumn("meter_no");
        model.addColumn("purpose"); 
        model.addColumn("deposit");
        model.addColumn("loads");
        model.addColumn("elec_board_id");
        model.addColumn("elec_board_name");
        model.addColumn("elec_board_address");
        model.addColumn("location_id"); 
        model.addColumn("incharge"); 
         try
        {
              consstmt = cons.Getconnection().createStatement();
        ref_data();  
        }
        catch (Exception e){
            System.err.println(e);
        }
        constble.setModel(model);
        filltranCombo();
        fillmetCombo();
        filllocCombo();
        fillinchCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        conno = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        conname = new javax.swing.JTextField();
        dep = new javax.swing.JTextField();
        loa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        eadd = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        eidtxt = new javax.swing.JTextField();
        locid = new javax.swing.JComboBox();
        inch = new javax.swing.JComboBox();
        trans = new javax.swing.JComboBox();
        meter = new javax.swing.JComboBox();
        purp = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        updatebut = new javax.swing.JButton();
        insertbutt = new javax.swing.JButton();
        dltbutt = new javax.swing.JButton();
        exitbutt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        constble = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("KSEB SYSTEM - CONSUMER DETAILS ENTRY");

        jLabel8.setText("jLabel8");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Consumer number  :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Consumer name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Transformer no :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Meter no :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Purpose :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Deposit :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Elec board id :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Elec board name :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Elec board address :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Location id :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Incharge :");

        eadd.setEditable(false);

        ename.setEditable(false);

        eidtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eidtxtKeyPressed(evt);
            }
        });

        purp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Domestic", "Industrial" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Telephone :");

        updatebut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updatebut.setText("UPDATE");
        updatebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebutActionPerformed(evt);
            }
        });

        insertbutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertbutt.setText("INSERT");
        insertbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttActionPerformed(evt);
            }
        });

        dltbutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dltbutt.setText("DELETE");
        dltbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltbuttActionPerformed(evt);
            }
        });

        exitbutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitbutt.setText("EXIT");
        exitbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Loads :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conno, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meter, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 32, Short.MAX_VALUE)
                                .addComponent(eadd, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(locid, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inch, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(insertbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updatebut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dltbutt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exitbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(conno, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel11))
                    .addComponent(eidtxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(conname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eadd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel14))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(inch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(meter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(purp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dep, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(loa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dltbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        constble.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        constble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "consumer_no", "consumer_details", "telephone", "transformer_no", "meter_no", "purpose", "deposit", "loads", "elec_board_id", "elec_board_name", "nullelec_board_address", "location_id", "incharge"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        constble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                constbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(constble);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttActionPerformed
        // TODO add your handling code here:
        String consumer_no = conno.getText();
        String consumer_name = conname.getText();
        String telephone = tel.getText();
        String transformer_no = trans.getSelectedItem().toString();
        String meter_no= meter.getSelectedItem().toString();
        String purpose = purp.getSelectedItem().toString();
        String deposit = dep.getText();
        String loads =loa.getText();
        String elec_board_id =eidtxt.getText();
        String elec_board_name =ename.getText();
        String elec_board_address =eadd.getText();
        String location_id = locid.getSelectedItem().toString();
        String incharge = inch.getSelectedItem().toString();
        
        try {
            
            PreparedStatement ps = cons.Getconnection().prepareStatement("insert into consumer_master (consumer_no,consumer_name,telephone,transformer_no,meter_no,purpose,deposit,loads,elec_board_id,elec_board_name,elec_board_address,location_id,incharge)values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, consumer_no);
            ps.setString(2, consumer_name);
            ps.setString(3, telephone);
            ps.setString(4, transformer_no);
            ps.setString(5,  meter_no);
            ps.setString(6, purpose);            
            ps.setString(7, deposit);
            ps.setString(8, loads);
            ps.setString(9, elec_board_id);
            ps.setString(10, elec_board_name); 
            ps.setString(11, elec_board_address); 
            ps.setString(12, location_id );
            ps.setString(13, incharge);
            ps.executeUpdate ();
            JOptionPane.showMessageDialog(null, "Data Inserted Successfully");
            ref_data();
            conno.setText("");
            conname.setText("");
            tel.setText("");
            trans.setSelectedItem(0);
            meter.setSelectedItem(0);
            purp.setSelectedItem(0);
            dep.setText("");
            loa.setText("");
            eidtxt.setText("");
            ename.setText("");
            eadd.setText("");
            locid.setSelectedItem(0);
            inch.setSelectedItem(0);
           
        }
     catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to insert data: " + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_insertbuttActionPerformed

    private void updatebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebutActionPerformed
        // TODO add your handling code here:
       try{ 
            PreparedStatement ps;
            ps=cons.Getconnection().prepareStatement("update consumer_master set consumer_name=?,telephone=?,transformer_no=?,meter_no=?,purpose=?,deposit=?,loads=?,elec_board_id=?,elec_board_name=?,elec_board_address=?,location_id=?,incharge=? where consumer_no=?");
           ps.setString(1,conname.getText());
            ps.setString(2,tel.getText());
            ps.setString(3,trans.getSelectedItem().toString());
            ps.setString(4,meter.getSelectedItem().toString());
            ps.setString(5, purp.getSelectedItem().toString());
            ps.setString(6,dep.getText());
            ps.setString(7,loa.getText());
            ps.setString(8,eidtxt.getText());
            ps.setString(9,ename.getText());
            ps.setString(10,eadd.getText());
            ps.setString(11, locid.getSelectedItem().toString());
            ps.setString(12,inch.getSelectedItem().toString());
            ps.setString(13,conno.getText()); 
            
        if (JOptionPane.showConfirmDialog (null,"Confirm Modification","modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            ps.executeUpdate();
            ref_data();
            conno.setText("");
            conname.setText("");
            tel.setText("");
            trans.setSelectedItem(0);
            meter.setSelectedItem(0);
            purp.setSelectedItem(0);
            dep.setText("");
            loa.setText("");
            eidtxt.setText("");
            ename.setText("");
            eadd.setText("");
            locid.setSelectedItem(0);
            inch.setSelectedItem(0);
            
            JOptionPane.showMessageDialog(null, "Data Updated Successfully");
        }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Unable to update :" + e.getLocalizedMessage());
            }        
                                                
                                         
    }//GEN-LAST:event_updatebutActionPerformed

    private void dltbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltbuttActionPerformed
        // TODO add your handling code here:
         String dsql  = "Delete from consumer_master where consumer_no = '" + conno.getText() + "'" ;
        try {
            if (JOptionPane.showConfirmDialog(this, "Attention You are going to delete consumer information","Delete electricity_board",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            if (conno.getText().length() !=0){
            consstmt.executeUpdate(dsql);
            ref_data();
            conno.setText("");
            conname.setText("");
            tel.setText("");
            trans.setSelectedItem(0);
            meter.setSelectedItem(0);
            purp.setSelectedItem(0);
            dep.setText("");
            loa.setText("");
            eidtxt.setText("");
            ename.setText("");
            eadd.setText("");
            locid.setSelectedItem(0);
            inch.setSelectedItem(0);
           
            JOptionPane.showMessageDialog(this,"Record Deleted Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this,"Enter Id value to delete..");
    
                 }    
             }
    }                                          
    catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unable to Delete:" + e.getLocalizedMessage());
        }
        
        
    }//GEN-LAST:event_dltbuttActionPerformed
  private JFrame frame;
    private void exitbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm to exit","elebill_system",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_exitbuttActionPerformed

     private void filltranCombo() {
         try{
            PreparedStatement ps = cons.Getconnection().prepareStatement("select transformer_no from transformer_master");
            consrst = ps.executeQuery();
            while(consrst.next()){
                trans.addItem(consrst.getString(1));
            }
        }
        catch (Exception e){
            System.err.println(e);
        } 
     }
    
     private void fillmetCombo() {
         try{
            PreparedStatement ps = cons.Getconnection().prepareStatement("select meter_no from meter_master");
            consrst = ps.executeQuery();
            while(consrst.next()){
                meter.addItem(consrst.getString(1));
            }
        }
        catch (Exception e){
            System.err.println(e);
        } 
     }
     private void filllocCombo() {
         try{
            PreparedStatement ps = cons.Getconnection().prepareStatement("select location_id from location_master");
            consrst = ps.executeQuery();
            while(consrst.next()){
                locid.addItem(consrst.getString(1));
            }
        }
        catch (Exception e){
            System.err.println(e);
        } 
     }
     private void fillinchCombo() {
         try{
            PreparedStatement ps = cons.Getconnection().prepareStatement("select employee_name from employee_master");
            consrst = ps.executeQuery();
            while(consrst.next()){
                inch.addItem(consrst.getString(1));
            }
        }
        catch (Exception e){
            System.err.println(e);
        } 
     }
    
     public void movedata (int i){
        try{
            conno.setText(model.getValueAt(i, 0).toString());
            conname.setText(model.getValueAt(i ,1).toString());
            tel.setText(model.getValueAt(i ,2).toString());
            trans.setSelectedItem(model.getValueAt(i ,3).toString());
            meter.setSelectedItem(model.getValueAt(i ,4).toString());
            purp.setSelectedItem(model.getValueAt(i ,5).toString());
            dep.setText(model.getValueAt(i ,6).toString());
            loa.setText(model.getValueAt(i ,7).toString());
            eidtxt.setText(model.getValueAt(i ,8).toString());   
            ename.setText(model.getValueAt(i ,9).toString()); 
            eadd.setText(model.getValueAt(i ,10).toString()); 
            locid.setSelectedItem(model.getValueAt(i ,11).toString());
            inch.setSelectedItem(model.getValueAt(i ,12).toString());
        }
        catch (Exception e){
    System.err.println(e);
        JOptionPane.showMessageDialog(null,"Error in moving" + e.getLocalizedMessage());
    }
    
    }
    private void constbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_constbleMouseClicked
        // TODO add your handling code here:
        try{
        int i=this.constble.getSelectedRow();
        movedata(i);
    } 
    catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error moving Data" + e.getLocalizedMessage());
    }
                                        
    }//GEN-LAST:event_constbleMouseClicked

    private void eidtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eidtxtKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           disp_board_details(); 
        }
    }//GEN-LAST:event_eidtxtKeyPressed
 
    
   private void disp_board_details() {
       String eid=eidtxt.getText();
       try
       {
           PreparedStatement ps =cons.Getconnection().prepareStatement("select elec_board_name,elec_board_address" + " from electricity_board_master where elec_board_id=?");
           ps.setString(1,eid);
           consrst=ps.executeQuery();
           if(consrst.next() ){
               ename.setText(consrst.getString("elec_board_name"));
               eadd.setText(consrst.getString("elec_board_address"));
         }
       }
           catch(Exception ex){
                 
                   Logger.getLogger(Consumer_entry.class.getName()).log(Level.SEVERE, null, ex);
                   }
       }
    
    private void ref_data() {
        try {
         model.setRowCount(0);
        consrst = consstmt.executeQuery("select * from consumer_master");
        while(consrst.next ()) {
        model.addRow(new Object[]
        {consrst.getString("consumer_no"),consrst.getString("consumer_name"),consrst.getString("telephone"),consrst.getString("transformer_no"),consrst.getString("meter_no"),consrst.getString("purpose"),consrst.getString("deposit"),consrst.getString("loads"),consrst.getString("elec_board_id"),consrst.getString("elec_board_name"),consrst.getString("elec_board_address"),consrst.getString("location_id"),consrst.getString("incharge")});
         }
        }
         catch (Exception e){
             System.err.println(e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consumer_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consumer_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consumer_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consumer_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consumer_entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conname;
    private javax.swing.JTextField conno;
    private javax.swing.JTable constble;
    private javax.swing.JTextField dep;
    private javax.swing.JButton dltbutt;
    private javax.swing.JTextField eadd;
    private javax.swing.JTextField eidtxt;
    private javax.swing.JTextField ename;
    private javax.swing.JButton exitbutt;
    private javax.swing.JComboBox inch;
    private javax.swing.JButton insertbutt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loa;
    private javax.swing.JComboBox locid;
    private javax.swing.JComboBox meter;
    private javax.swing.JComboBox purp;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox trans;
    private javax.swing.JButton updatebut;
    // End of variables declaration//GEN-END:variables

   
  
}

