
import java.awt.event.KeyEvent;
import static java.lang.Compiler.command;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author swlab
 */
public class department_entry extends javax.swing.JFrame {

    /**
     * Creates new form department_entry
     */
     ksebdb dept = new ksebdb();
     Statement deptstmt;
     ResultSet deptrst;
     DefaultTableModel model = new DefaultTableModel();
     public department_entry() {
        initComponents();
        model.addColumn("Department_id");
        model.addColumn("Department_name");
        model.addColumn("Dept_manager_id");
        model.addColumn("Location_id");
        model.addColumn("Dept_location");
        try
        {
            deptstmt = dept.Getconnection().createStatement();
         ref_data();     
        }
        catch (Exception e){
            System.err.println(e);
        }
        tbldept.setModel(model);
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dptidtxt = new javax.swing.JTextField();
        deptnametxt = new javax.swing.JTextField();
        deptmantxt = new javax.swing.JTextField();
        txtlocid = new javax.swing.JTextField();
        txtdept = new javax.swing.JTextField();
        updatebutt = new javax.swing.JButton();
        insertbutt = new javax.swing.JButton();
        deletebutt = new javax.swing.JButton();
        exitbuttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldept = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("KSEB SYSTEM - DEPARTMENT ENTRY");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Department id :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Department name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Department manager id :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Location id :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Department location :");

        dptidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dptidtxtActionPerformed(evt);
            }
        });

        deptnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptnametxtActionPerformed(evt);
            }
        });

        deptmantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptmantxtActionPerformed(evt);
            }
        });

        txtlocid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocidActionPerformed(evt);
            }
        });
        txtlocid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlocidKeyPressed(evt);
            }
        });

        txtdept.setEditable(false);

        updatebutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebutt.setText("UPDATE");
        updatebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttActionPerformed(evt);
            }
        });

        insertbutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insertbutt.setText("INSERT");
        insertbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttActionPerformed(evt);
            }
        });

        deletebutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebutt.setText("DELETE");
        deletebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttActionPerformed(evt);
            }
        });

        exitbuttn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbuttn.setText("EXIT");
        exitbuttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insertbutt)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatebutt)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdept, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deptmantxt)
                    .addComponent(deptnametxt)
                    .addComponent(dptidtxt)
                    .addComponent(txtlocid)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(deletebutt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitbuttn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dptidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(deptnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(deptmantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtlocid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtdept, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbuttn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        tbldept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbldept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department_id", "Department_name", "Dept_manager_id", "Location_id", "Dept_location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbldept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldeptMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldept);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deptnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptnametxtActionPerformed

    private void insertbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttActionPerformed
        String Department_id = dptidtxt.getText();
        String Department_name = deptnametxt.getText();
        String Dept_manager_id = deptmantxt.getText();
        String Location_id = txtlocid.getText();
        String Dept_location = txtdept.getText();
        try {
            
            PreparedStatement ps = dept.Getconnection().prepareStatement("insert into department_master (Department_id,Department_name,Dept_manager_id,Location_id,Dept_location) values (?,?,?,?,?)");
            ps.setString(1,Department_id  );
            ps.setString(2,Department_name );
            ps.setString(3,Dept_manager_id  );
            ps.setString(4,Location_id);
            ps.setString(5,Dept_location);
            ps.executeUpdate ();
           JOptionPane.showMessageDialog (null, "Data Inserted Successfully");
        ref_data();   
        dptidtxt.setText("");
        deptnametxt.setText("");
        deptmantxt.setText("");
        txtlocid.setText("");
        txtdept.setText("");
        }
        catch (Exception e){           
            JOptionPane.showMessageDialog (null, "Unable to insert data: " + e.getLocalizedMessage());
        }
   
    }//GEN-LAST:event_insertbuttActionPerformed

    private void dptidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dptidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dptidtxtActionPerformed

    private void deptmantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptmantxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptmantxtActionPerformed

    private void updatebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttActionPerformed
    try{ 
            PreparedStatement ps;
            ps=dept.Getconnection().prepareStatement("update department_master set Department_name=?,Dept_manager_id =?,Location_id=?,Dept_location=? where Department_id=?");
            ps.setString(1,deptnametxt.getText());
            ps.setString(2,deptmantxt.getText());
            ps.setString(3,txtlocid.getText());
            ps.setString(4,txtdept.getText());
            ps.setString(5,dptidtxt.getText());
            
        if (JOptionPane.showConfirmDialog (null,"Confirm Modification","modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            ps.executeUpdate();
            ref_data();
            deptnametxt.setText("");
            deptmantxt.setText("");
            txtlocid.setText("");
            txtdept.setText("");
            dptidtxt.setText("");
            JOptionPane.showMessageDialog(null, "Data Updated Successfully");
        }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Unable to update :" + e.getLocalizedMessage());
            }        
                                                   // TODO add your handling code here:
    }//GEN-LAST:event_updatebuttActionPerformed

    private void txtlocidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocidActionPerformed

    private void deletebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttActionPerformed
      
        String dsql  = "Delete from department_master where department_id = '" + dptidtxt.getText() + "'" ;
        try {
            if (JOptionPane.showConfirmDialog(this, "Attention You are going to delete location information","Delete department",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            if (dptidtxt.getText().length() !=0){
            deptstmt.executeUpdate(dsql);
            ref_data();
            dptidtxt.setText("");
            deptnametxt.setText("");
            deptmantxt.setText("");
            txtlocid.setText("");
            txtdept.setText("");
            JOptionPane.showMessageDialog(this,"Record Deleted Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this,"Enter Id value to delete..");
    
                 }    
              }
           }
        catch (Exception e) { 
           JOptionPane.showMessageDialog(this, "Unable to Delete:" + e.getLocalizedMessage());
        }  // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttActionPerformed
    private JFrame frame;
    private void exitbuttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttnActionPerformed
     
        frame=new JFrame("exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm to exit","elebill_system",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
             this.setVisible(false);
        }
        
                                   // TODO add your handling code here:
    }//GEN-LAST:event_exitbuttnActionPerformed
public void movedata (int i){
        try{
           dptidtxt.setText(model.getValueAt(i, 0).toString());
           deptnametxt.setText(model.getValueAt(i ,1).toString());
           deptmantxt.setText(model.getValueAt(i ,2).toString());
           txtlocid.setText(model.getValueAt(i ,3).toString());
           txtdept.setText(model.getValueAt(i ,4).toString());
        }
        catch (Exception e){
    System.err.println(e);
        JOptionPane.showMessageDialog(null,"Error in moving" + e.getLocalizedMessage());
    }
}
    private void tbldeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldeptMouseClicked
           
       // TODO add your handling code here:
           try{
        int i=this.tbldept.getSelectedRow();
        movedata(i);
    } 
    catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error moving Data" + e.getLocalizedMessage());
    }
    }//GEN-LAST:event_tbldeptMouseClicked

    private void txtlocidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlocidKeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           disp_location_details(); 
        }
    }                                 
 
    
   private void disp_location_details() {
       String loc =txtlocid.getText();
       try
       {
           PreparedStatement ps =dept.Getconnection().prepareStatement("select location_name " + " from location_master where location_id=?");
           ps.setString(1,loc);
           deptrst=ps.executeQuery();
           if(deptrst.next() ){
               txtdept.setText(deptrst.getString("location_name"));
              
         }
       }
           catch(Exception ex){
                 
                   Logger.getLogger(Consumer_entry.class.getName()).log(Level.SEVERE, null, ex);
                   }
       
      
    }//GEN-LAST:event_txtlocidKeyPressed

      private void ref_data() {
     try {
        model.setRowCount(0);
        deptrst = deptstmt.executeQuery("select * from department_master");
        while(deptrst.next ()) {
        model.addRow(new Object[]
        {deptrst.getString("Department_id"),deptrst.getString("Department_name"),deptrst.getString("Dept_manager_id"),deptrst.getString("Location_id"),deptrst.getString("Dept_location")});
         }
        }
         catch (Exception e){
             System.err.println(e);
         }
      }

    /**
      * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(department_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(department_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(department_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(department_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new department_entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebutt;
    private javax.swing.JTextField deptmantxt;
    private javax.swing.JTextField deptnametxt;
    private javax.swing.JTextField dptidtxt;
    private javax.swing.JButton exitbuttn;
    private javax.swing.JButton insertbutt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldept;
    private javax.swing.JTextField txtdept;
    private javax.swing.JTextField txtlocid;
    private javax.swing.JButton updatebutt;
    // End of variables declaration//GEN-END:variables
    }                
