

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author swlab
 */
public class elecboard_entry extends javax.swing.JFrame {

    /**
     
     */
    ksebdb ele = new ksebdb();
         Statement elestmt;
         ResultSet elerst; 
         DefaultTableModel model = new DefaultTableModel();
         String varactive=null;
         public elecboard_entry() {   
         initComponents();
          model.addColumn("elec_board_id");
          model.addColumn("elec_board_name");
          model.addColumn("elec_board_address");
          model.addColumn("telephone");
          model.addColumn("location_id");
          model.addColumn("Location_name");
          model.addColumn("incharge");
          model.addColumn("active");
            try
        {
            elestmt = ele.Getconnection().createStatement();
        ref_data();  
        }
        catch (Exception e){
            System.err.println(e);
        }
        eltble.setModel(model);
       
        fillempcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eleidtxt = new javax.swing.JTextField();
        elntxt = new javax.swing.JTextField();
        eltetxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        eladdtxt = new javax.swing.JTextArea();
        locntxt = new javax.swing.JTextField();
        updatebutt = new javax.swing.JButton();
        insertbutt = new javax.swing.JButton();
        deletebutt = new javax.swing.JButton();
        rbyes = new javax.swing.JRadioButton();
        rbno = new javax.swing.JRadioButton();
        exitbutt = new javax.swing.JButton();
        incharget = new javax.swing.JComboBox();
        varacti = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        eltble = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("KSEB SYSTEM - ELECTRICITY BOARD ENTRY");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Electricity board id :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Electricity board address :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Telephone :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Location id :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Location name :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Electricity board name :");

        eltetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eltetxtActionPerformed(evt);
            }
        });

        eladdtxt.setColumns(20);
        eladdtxt.setRows(5);
        jScrollPane1.setViewportView(eladdtxt);

        locntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locntxtActionPerformed(evt);
            }
        });

        updatebutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updatebutt.setText("UPDATE");
        updatebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttActionPerformed(evt);
            }
        });

        insertbutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertbutt.setText("INSERT");
        insertbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttActionPerformed(evt);
            }
        });

        deletebutt.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        deletebutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deletebutt.setText("DELETE");
        deletebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbyes);
        rbyes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbyes.setText("YES");
        rbyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbyesActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbno);
        rbno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbno.setText("NO");

        exitbutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitbutt.setText("EXIT");
        exitbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttActionPerformed(evt);
            }
        });

        incharget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inchargetActionPerformed(evt);
            }
        });

        varacti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        varacti.setText("Active :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText(" Incharge :");

        loc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locMouseClicked(evt);
            }
        });
        loc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                locKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(insertbutt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(updatebutt)))
                                .addGap(11, 11, 11)
                                .addComponent(deletebutt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exitbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel4))
                                        .addGap(0, 84, Short.MAX_VALUE))
                                    .addComponent(varacti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eltetxt)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                    .addComponent(elntxt)
                                    .addComponent(eleidtxt)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbyes)
                                        .addGap(38, 38, 38)
                                        .addComponent(rbno))
                                    .addComponent(locntxt)
                                    .addComponent(incharget, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(loc))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(612, 612, 612))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(eleidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(eltetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(locntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(incharget, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(varacti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbyes)
                        .addComponent(rbno)))
                .addGap(18, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        eltble.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        eltble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Elec_board_id", "Elec_board_name", "Elec_board_address", "Telephone", "Location_id", "Location_name", "Incharge", "Active"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        eltble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eltbleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(eltble);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(273, 273, 273))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(82, 82, 82))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eltetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eltetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eltetxtActionPerformed

    private void locntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locntxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locntxtActionPerformed

    private void inchargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inchargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inchargetActionPerformed

    private void insertbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttActionPerformed
        // TODO add your handling code here:
        
         String elec_board_id = eleidtxt.getText();
         String elec_board_name = elntxt.getText();
         String elec_board_address = eladdtxt.getText();
         String telephone = eltetxt.getText();
         String location_id =  loc.getText();
         String location_name = locntxt.getText();
         String incharge = incharget.getSelectedItem().toString();
     
         if (rbyes.isSelected()){
             varactive = "YES";
         } else {
              varactive = "NO";
         }
         
        try {
            
            PreparedStatement ps = ele.Getconnection().prepareStatement("insert into electricity_board_master (elec_board_id,elec_board_name,elec_board_address,telephone,location_id,location_name,incharge,active) values (?,?,?,?,?,?,?,?)");
            ps.setString(1, elec_board_id);
            ps.setString(2, elec_board_name);
            ps.setString(3, elec_board_address);
            ps.setString(4, telephone);
            ps.setString(5, location_id);
            ps.setString(6, location_name);
            ps.setString(7, incharge);
            ps.setString(8,varactive);
            ps.executeUpdate();
            JOptionPane.showMessageDialog (null, "Data Inserted Successfully");
            ref_data();
            eleidtxt.setText("");
            elntxt.setText("");
            eladdtxt.setText("");
            eltetxt.setText("");
            loc.setText("");
            locntxt.setText("");
            incharget.setSelectedItem(0);
            rbyes.setSelected(true);
           
        }
    
        catch (Exception e){           
            JOptionPane.showMessageDialog (null, "Unable to insert data: " + e.getLocalizedMessage());
       
    }//GEN-LAST:event_insertbuttActionPerformed
    }
    private void rbyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbyesActionPerformed

    private void updatebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttActionPerformed
    // TODO add your handling code here:
          try{ 
              if (rbyes.isSelected()){
                  varactive="YES";
              }
              else{
                  varactive="NO";
              }
          
            PreparedStatement ps;
            ps=ele.Getconnection().prepareStatement("update electricity_board_master set elec_board_name=?,elec_board_address=?,telephone=?, location_id=?, location_name=?,incharge=?,active=?  where elec_board_id=?");
            ps.setString(1,elntxt.getText());
            ps.setString(2,eladdtxt.getText());
            ps.setString(3,eltetxt.getText());
            ps.setString(4,loc.getText());
            ps.setString(5,locntxt.getText());
            ps.setString(6,incharget.getSelectedItem().toString());
            ps.setString(7,varactive);
            ps.setString(8,eleidtxt.getText());
        
           if (JOptionPane.showConfirmDialog (null,"Confirm Modification","modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            ps.executeUpdate();
            ref_data();
            elntxt.setText("");
            eladdtxt.setText("");
            eltetxt.setText("");
            loc.setText("");
            locntxt.setText("");
            incharget.setSelectedItem(0);
            rbyes.setSelected(true);
            eleidtxt.setText("");
             JOptionPane.showMessageDialog(null, "Data Updated Successfully");
           }
          }
          catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Unable to update :" + e.getLocalizedMessage());
                  }
          
    }//GEN-LAST:event_updatebuttActionPerformed
    
    private void deletebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttActionPerformed
        // TODO add your handling code here:
          String dsql  = "Delete from electricity_board_master where elec_board_id = '" + eleidtxt.getText() + "'" ;
        try {
            if (JOptionPane.showConfirmDialog(this, "Attention You are going to delete electricity information","Delete electricity_board",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            if (eleidtxt.getText().length() !=0){
            elestmt.executeUpdate(dsql);
            ref_data();
            eleidtxt.setText("");
            elntxt.setText("");
            eladdtxt.setText("");
            eltetxt.setText("");
             loc.setText("");
            locntxt.setText("");
            incharget.setSelectedItem(0);
            rbyes.setSelected(true);
           
            JOptionPane.showMessageDialog(this,"Record Deleted Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this,"Enter Id value to delete..");
    
                 }    
             }
    }//GEN-LAST:event_deletebuttActionPerformed
    catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unable to Delete:" + e.getLocalizedMessage());
        }
    } 
    private JFrame frame;
    private void exitbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttActionPerformed
        // TODO add your handling code here:
       frame=new JFrame("exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm to exit","elebill_system",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
             this.setVisible(false);
        } 
    }//GEN-LAST:event_exitbuttActionPerformed
 private void movedata(int i) {
     
   try{
           eleidtxt.setText(model.getValueAt(i ,0).toString());
           elntxt.setText(model.getValueAt(i ,1).toString());
           eladdtxt.setText(model.getValueAt(i ,2).toString());
           eltetxt.setText(model.getValueAt(i ,3).toString());
           loc.setText(model.getValueAt(i ,4).toString());
           locntxt.setText(model.getValueAt(i ,5).toString());
           incharget.setSelectedItem(model.getValueAt(1,6).toString());
        
           if((model.getValueAt(i,7).equals("YES"))){
           
              rbyes.setSelected(true);
    }else{
            rbno.setSelected(true);
            }
        }
        catch (Exception e){
    System.err.println(e);
        JOptionPane.showMessageDialog(null,"Error in moving" + e.getLocalizedMessage());
    }
 }
    private void eltbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eltbleMouseClicked
        // TODO add your handling code here:
     try{
        int i=this.eltble.getSelectedRow();
        movedata(i);
    } 
    catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error moving Data" + e.getLocalizedMessage());
    }                             
    }//GEN-LAST:event_eltbleMouseClicked

    private void locMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_locMouseClicked

    private void locKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locKeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           disp_locat_details(); 
        }
    }                                 
 
    
   private void disp_locat_details() {
       String loci =loc.getText();
       try
       {
           PreparedStatement ps =ele.Getconnection().prepareStatement("select location_name " + " from location_master where location_id=?");
           ps.setString(1,loci);
           elerst=ps.executeQuery();
           if(elerst.next() ){
               locntxt.setText(elerst.getString("location_name"));
              
         }
       }
           catch(Exception ex){
                 
                   Logger.getLogger(Consumer_entry.class.getName()).log(Level.SEVERE, null, ex);
                   }
       
      
    }//GEN-LAST:event_locKeyPressed
  private void fillempcombo() {
    try{
            PreparedStatement ps = ele.Getconnection().prepareStatement("select employee_name from employee_master");
            elerst = ps.executeQuery();
            while(elerst.next()){
                incharget.addItem(elerst.getString(1));
            }
        }
        catch (Exception e){
            System.err.println(e);
   
    
}
    
}      
   //To change body of generated methods, choose Tools | Templates.

 
    
    private void ref_data() {
     try {
         model.setRowCount(0);
        elerst = elestmt.executeQuery("select * from electricity_board_master");
        while(elerst.next ()) {
        model.addRow(new Object[]
        {elerst.getString("elec_board_id"),elerst.getString("elec_board_name"),elerst.getString("elec_board_address"),elerst.getString("telephone"),elerst.getString("location_id"),elerst.getString("location_name"),elerst.getString("incharge"),elerst.getString("active")});
         }
        }
         catch (Exception e){
             System.err.println(e);
        }
}    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new elecboard_entry().setVisible(true);
            }
        
        });
                    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deletebutt;
    private javax.swing.JTextArea eladdtxt;
    private javax.swing.JTextField eleidtxt;
    private javax.swing.JTextField elntxt;
    private javax.swing.JTable eltble;
    private javax.swing.JTextField eltetxt;
    private javax.swing.JButton exitbutt;
    private javax.swing.JComboBox incharget;
    private javax.swing.JButton insertbutt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField loc;
    private javax.swing.JTextField locntxt;
    private javax.swing.JRadioButton rbno;
    private javax.swing.JRadioButton rbyes;
    private javax.swing.JButton updatebutt;
    private javax.swing.JLabel varacti;
    // End of variables declaration//GEN-END:variables

}