/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        loc = new javax.swing.JMenuItem();
        dept = new javax.swing.JMenuItem();
        meter = new javax.swing.JMenuItem();
        empl = new javax.swing.JMenuItem();
        elecb = new javax.swing.JMenuItem();
        transf = new javax.swing.JMenuItem();
        met = new javax.swing.JMenuItem();
        cons = new javax.swing.JMenuItem();
        consumpt = new javax.swing.JMenuItem();
        paym = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        abt = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("ELECTRICITY BILL MANAGEMENT ");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pp.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 710));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jDesktopPane1);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 90, 150, 750));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bill.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 990, 620));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1390, 130));

        jMenuBar1.setFont(new java.awt.Font("Showcard Gothic", 0, 15)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText(" Home ");
        jMenu1.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("  Master ");
        jMenu2.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N

        loc.setText("Location entry");
        loc.setBorderPainted(true);
        loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locActionPerformed(evt);
            }
        });
        jMenu2.add(loc);

        dept.setText("Department entry");
        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });
        jMenu2.add(dept);

        meter.setText("Job entry");
        meter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterActionPerformed(evt);
            }
        });
        jMenu2.add(meter);

        empl.setText("Employee entry");
        empl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emplActionPerformed(evt);
            }
        });
        jMenu2.add(empl);

        elecb.setText("Electricity board entry");
        elecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elecbActionPerformed(evt);
            }
        });
        jMenu2.add(elecb);

        transf.setText("Transformer entry");
        transf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfActionPerformed(evt);
            }
        });
        jMenu2.add(transf);

        met.setText("Meter entry");
        met.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metActionPerformed(evt);
            }
        });
        jMenu2.add(met);

        cons.setText("Consumer entry");
        cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consActionPerformed(evt);
            }
        });
        jMenu2.add(cons);

        consumpt.setText("Consumption entry");
        consumpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumptActionPerformed(evt);
            }
        });
        jMenu2.add(consumpt);

        paym.setText("Payment entry");
        paym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymActionPerformed(evt);
            }
        });
        jMenu2.add(paym);

        jMenuBar1.add(jMenu2);

        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setText("   Help ");
        jMenu4.setFont(new java.awt.Font("Segoe UI Black", 0, 15)); // NOI18N

        abt.setText("About");
        abt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtActionPerformed(evt);
            }
        });
        jMenu4.add(abt);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu4.add(logout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
        // TODO add your handling code here:
      new Location_entry().setVisible(true);    
    }//GEN-LAST:event_locActionPerformed

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        // TODO add your handling code here:
        new department_entry().setVisible(true);
    }//GEN-LAST:event_deptActionPerformed

    private void emplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emplActionPerformed
        // TODO add your handling code here:
         new employee_entry().setVisible(true);
    }//GEN-LAST:event_emplActionPerformed

    private void meterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterActionPerformed
        // TODO add your handling code here:
         new job_entry().setVisible(true);
    }//GEN-LAST:event_meterActionPerformed

    private void elecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elecbActionPerformed
        // TODO add your handling code here:
         new elecboard_entry().setVisible(true);
    }//GEN-LAST:event_elecbActionPerformed

    private void transfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfActionPerformed
        // TODO add your handling code here:
         new transformer_entry().setVisible(true);
    }//GEN-LAST:event_transfActionPerformed

    private void metActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metActionPerformed
        // TODO add your handling code here:
         new Meter_entry().setVisible(true);
    }//GEN-LAST:event_metActionPerformed

    private void consActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consActionPerformed
        // TODO add your handling code here:
      new Consumer_entry().setVisible(true);
    }//GEN-LAST:event_consActionPerformed

    private void consumptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumptActionPerformed
        // TODO add your handling code here:
         new consumption().setVisible(true);
    }//GEN-LAST:event_consumptActionPerformed

    private void paymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymActionPerformed
        // TODO add your handling code here:
         new payment_entry().setVisible(true);
    }//GEN-LAST:event_paymActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       
    }//GEN-LAST:event_logoutActionPerformed

    private void abtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtActionPerformed
        // TODO add your handling code here:
         new About().setVisible(true);
         
    }//GEN-LAST:event_abtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abt;
    private javax.swing.JMenuItem cons;
    private javax.swing.JMenuItem consumpt;
    private javax.swing.JMenuItem dept;
    private javax.swing.JMenuItem elecb;
    private javax.swing.JMenuItem empl;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem loc;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem met;
    private javax.swing.JMenuItem meter;
    private javax.swing.JMenuItem paym;
    private javax.swing.JMenuItem transf;
    // End of variables declaration//GEN-END:variables
}
