

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author swlab
 */
public class payment_entry extends javax.swing.JFrame {

    /**
     
     * Creates new form payment_entry
     */
    
     ksebdb pay = new ksebdb();
     Statement paystmt;
     ResultSet payrst;
     DefaultTableModel model = new DefaultTableModel();
    public payment_entry() {
        initComponents();
        model.addColumn("receipt_no");
        model.addColumn("consumer_no");
        model.addColumn("consumer_name");
        model.addColumn("due_date");
        model.addColumn("bill_number");
        model.addColumn("bill_amount");
        model.addColumn("payment_mode");
        model.addColumn("description");
        model.addColumn("paid_amount");
        model.addColumn("paid_date"); 
        model.addColumn("balance_amount");
       try
        {
            paystmt = pay.Getconnection().createStatement();
         ref_data();     
        }
        catch (Exception e){
            System.err.println(e);
        }
        payt.setModel(model);
    }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cna = new javax.swing.JTextField();
        bno = new javax.swing.JTextField();
        bamt = new javax.swing.JTextField();
        pamt = new javax.swing.JTextField();
        blamt = new javax.swing.JTextField();
        updatebutt = new javax.swing.JButton();
        insertbutt = new javax.swing.JButton();
        deletebutt = new javax.swing.JButton();
        exitbutt = new javax.swing.JButton();
        pd = new com.toedter.calendar.JDateChooser();
        dd = new com.toedter.calendar.JDateChooser();
        rn = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pcomb = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        payt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("KSEB SYSTEM - PAYMENT ENTRY");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Consumer name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Receipt number :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Due date :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Bill number :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Bill amount :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Paid amount :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Paid date :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Balance amount :");

        cna.setEditable(false);
        cna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnaActionPerformed(evt);
            }
        });

        bno.setEditable(false);
        bno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnoActionPerformed(evt);
            }
        });
        bno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bnoKeyPressed(evt);
            }
        });

        bamt.setEditable(false);

        updatebutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebutt.setText("UPDATE");
        updatebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttActionPerformed(evt);
            }
        });

        insertbutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insertbutt.setText("INSERT");
        insertbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttActionPerformed(evt);
            }
        });

        deletebutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebutt.setText("DELETE");
        deletebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttActionPerformed(evt);
            }
        });

        exitbutt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbutt.setText("EXIT");
        exitbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttActionPerformed(evt);
            }
        });

        cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnActionPerformed(evt);
            }
        });
        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Consumer number :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Payment mode :");

        pcomb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "online", "cash", "creditcard" }));
        pcomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcombActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Description :");

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(insertbutt)
                        .addGap(18, 18, 18)
                        .addComponent(updatebutt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(deletebutt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exitbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(pamt)
                                    .addComponent(blamt)
                                    .addComponent(dd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pcomb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cn, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(cna, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rn)
                                .addComponent(bno, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bamt, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcomb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pamt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(blamt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(cna, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(pd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bamt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(20, 20, 20)))
                        .addGap(44, 44, 44)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        payt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        payt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receipt_no", "consumer_no", "consumer_name", "duedate", "bill_amt", "bill_no", "payment_mode", "description", "paid_amt", "paid_date", "balance_amt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        payt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paytMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(payt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnActionPerformed

    private void bnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnoActionPerformed

    private void updatebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttActionPerformed
        // TODO add your handling code here:
          try{ 
            PreparedStatement ps;
            ps=pay.Getconnection().prepareStatement("update payment_master set consumer_no=?,consumer_name=?,due_date=?,bill_number=?,bill_amount=?,payment_mode=?,description=?,paid_amount=?,paid_date=?,balance_amount=? where receipt_no=?");
            ps.setString(1,cn.getText());
            ps.setString(2,cna.getText());
            SimpleDateFormat sdt = new SimpleDateFormat("yyyy-MM-dd");
            String dated = sdt.format(pd.getDate());
            ps.setString(3,dated);
            ps.setString(4,bno.getText());
            ps.setString(5,bamt.getText());
            ps.setString(6,pcomb.getSelectedItem().toString());
            ps.setString(7,desc.getText());
            ps.setString(8,pamt.getText());
            SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
            String datep = sd.format(dd.getDate());
            ps.setString(9,datep);
            ps.setString(10,blamt.getText());
            ps.setString(11,rn.getText());

        if (JOptionPane.showConfirmDialog (null,"Confirm Modification","modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            ps.executeUpdate();
           ref_data();
           rn.setText("");
           cn.setText("");
           cna.setText("");
           pd.setDate(null);
           bno.setText("");
           bamt.setText("");
           pcomb.setSelectedItem(0);
           desc.setText("");
           pamt.setText("");
           dd.setDate(null);
           blamt.setText("");
           
            JOptionPane.showMessageDialog(null, "Data Updated Successfully");
        } 
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Unable to update :" + e.getLocalizedMessage());
            }        
            
    }//GEN-LAST:event_updatebuttActionPerformed
          
                
    
    private void cnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnaActionPerformed

    private void insertbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttActionPerformed
        // TODO add your handling code here:
        String receipt_no = rn.getText();
        String consumer_no = cn.getText();
        String consumer_name= cna.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String due_date = sdf.format(pd.getDate());
        String bill_number = bno.getText();
        String bill_amount = bamt.getText();
        String payment_mode= pcomb.getSelectedItem().toString();
        String description= desc.getText();
        String paid_amount = pamt.getText();
        SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
        String paid_date = sdf.format(dd.getDate());
        String balance_amount = blamt.getText();
        try {
            
            PreparedStatement ps = pay.Getconnection().prepareStatement("insert into payment_master (receipt_no,consumer_no,consumer_name,due_date,bill_number,bill_amount,payment_mode,description,paid_amount,paid_date,balance_amount) values (?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1,receipt_no);
            ps.setString(2,consumer_no);
            ps.setString(3,consumer_name);
            ps.setString(4,due_date);
            ps.setString(5,bill_number);
            ps.setString(6,bill_amount);
            ps.setString(7,payment_mode);
            ps.setString(8,description);
            ps.setString(9,paid_amount);  
            ps.setString(10,paid_date);   
            ps.setString(11,balance_amount);         
            ps.executeUpdate ();
           JOptionPane.showMessageDialog (null, "Data Inserted Successfully");
           ref_data();
           rn.setText("");
           cn.setText("");
           cna.setText("");
           pd.setDate(null);
           bno.setText("");
           bamt.setText("");
           pcomb.setSelectedItem(0);
           desc.setText("");
           pamt.setText("");
           dd.setDate(null);
           blamt.setText("");
        }
        catch (Exception e){           
            JOptionPane.showMessageDialog (null, "Unable to insert data: " + e.getLocalizedMessage());
        }
       
    }//GEN-LAST:event_insertbuttActionPerformed

    private void cnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           disp_consumers_details(); 
        }
    }                                 
 
    
   private void disp_consumers_details() {
       String con =cn.getText();
       try
       {
           PreparedStatement ps =pay.Getconnection().prepareStatement("select consumer_name,due_date,bill_number,bill_amount " + " from consumption_master where consumer_no=?");
           ps.setString(1,con);
           payrst=ps.executeQuery();
           if(payrst.next() ){
               cna.setText(payrst.getString("consumer_name"));
               pd.setDate(payrst.getDate("due_date"));
               bno.setText(payrst.getString("bill_number"));
               bamt.setText(payrst.getString("bill_amount"));
               
         }
       }
           catch(Exception ex){
                 
                   Logger.getLogger(Consumer_entry.class.getName()).log(Level.SEVERE, null, ex);
                   }
       
      
    }//GEN-LAST:event_cnKeyPressed

    private void bnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bnoKeyPressed
    
    }//GEN-LAST:event_bnoKeyPressed
 private void movedata(int i) {
        try{
              rn.setText(model.getValueAt(i, 0).toString());
              cn.setText(model.getValueAt(i ,1).toString());
              cna.setText(model.getValueAt(i ,2).toString());
              Date dt = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i,3));
              pd.setDate(dt);
              bno.setText(model.getValueAt(i ,4).toString());
              bamt.setText(model.getValueAt(i ,5).toString());
              pcomb.setSelectedItem(model.getValueAt(i ,6).toString());
              desc.setText(model.getValueAt(i ,7).toString());
              pamt.setText(model.getValueAt(i ,8).toString());
              Date dts = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i,9));
              dd.setDate(dts);
              blamt.setText(model.getValueAt(i ,10).toString());
        }
        
        catch (Exception e){
    System.err.println(e);
        JOptionPane.showMessageDialog(null,"Error in moving" + e.getLocalizedMessage());
    }
     
     
 }
    private void paytMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paytMouseClicked
        // TODO add your handling code here:
        try{
        int i=this.payt.getSelectedRow();
        movedata(i);
    } 
    catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error moving Data" + e.getLocalizedMessage());
    }
    }//GEN-LAST:event_paytMouseClicked

    private void pcombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcombActionPerformed

    private void deletebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttActionPerformed
        // TODO add your handling code here:
        
        String dsql  = "Delete from payment_master where receipt_no = '" + rn.getText() + "'" ;
        try {
            if (JOptionPane.showConfirmDialog(this, "Attention You are going to delete payment information","Delete transformer details",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            if (rn.getText().length() !=0){
            paystmt.executeUpdate(dsql);
            ref_data();
           rn.setText("");
           cn.setText("");
           cna.setText("");
           pd.setDate(null);
           bno.setText("");
           bamt.setText("");
           pcomb.setSelectedItem(0);
           desc.setText("");
           pamt.setText("");
           dd.setDate(null);
           blamt.setText("");
            JOptionPane.showMessageDialog(this,"Record Deleted Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this,"Enter Id value to delete..");
    
                 }    
              }
        }
        catch (Exception e) { 
           JOptionPane.showMessageDialog(this, "Unable to Delete:" + e.getLocalizedMessage());
        }  
    }//GEN-LAST:event_deletebuttActionPerformed
   private JFrame frame;
    private void exitbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm to exit","elebill_system",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
        }
    }//GEN-LAST:event_exitbuttActionPerformed
 
    private void ref_data() {
       try {
        model.setRowCount(0);
        payrst = paystmt.executeQuery("select * from payment_master");
        while(payrst.next ()) {
        model.addRow(new Object[]
        {payrst.getString("receipt_no"),payrst.getString("consumer_no"),payrst.getString("consumer_name"),payrst.getString("due_date"),payrst.getString("bill_number"),payrst.getString("bill_amount"),payrst.getString("payment_mode"),payrst.getString("description"),payrst.getString("paid_amount"),payrst.getString("paid_date"),payrst.getString("balance_amount")});
         }
        }
         catch (Exception e){
             System.err.println(e);
         }
      
  } 
      
    
 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment_entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bamt;
    private javax.swing.JTextField blamt;
    private javax.swing.JTextField bno;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField cna;
    private com.toedter.calendar.JDateChooser dd;
    private javax.swing.JButton deletebutt;
    private javax.swing.JTextArea desc;
    private javax.swing.JButton exitbutt;
    private javax.swing.JButton insertbutt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pamt;
    private javax.swing.JTable payt;
    private javax.swing.JComboBox pcomb;
    private com.toedter.calendar.JDateChooser pd;
    private javax.swing.JTextField rn;
    private javax.swing.JButton updatebutt;
    // End of variables declaration//GEN-END:variables

  

    
}
