
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author swlab
 */
public class transformer_entry extends javax.swing.JFrame {

    /**
     * Creates new form transformer_entry
     */
    
     ksebdb tran = new ksebdb();
     Statement transtmt;
     ResultSet tranrst;
     DefaultTableModel model = new DefaultTableModel();
     public transformer_entry() {
        initComponents();
        model.addColumn("transformer_no");
        model.addColumn("transformer");
        model.addColumn("transformer_type");
        model.addColumn("capacity");
        model.addColumn("elec_board_id");
        model.addColumn("elec_board_name");
        try
        {
            transtmt = tran.Getconnection().createStatement();
         ref_data();     
        }
        catch (Exception e){
            System.err.println(e);
        }
        transt.setModel(model);
    }  
     

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tnotxt = new javax.swing.JTextField();
        ttxt = new javax.swing.JTextField();
        ttype = new javax.swing.JTextField();
        captxt = new javax.swing.JTextField();
        eleid = new javax.swing.JTextField();
        elename = new javax.swing.JTextField();
        updatebutt = new javax.swing.JButton();
        insertbutt = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        exitbutt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        transt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText(" KSEB SYSTEM - TRANSFORMER ENTRY");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Transformer number:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Transformer :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Transformer type :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Capacity :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Electricity board id :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Electricity board name :");

        tnotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ttxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttxtActionPerformed(evt);
            }
        });

        ttype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        captxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        eleid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eleid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eleidKeyPressed(evt);
            }
        });

        elename.setEditable(false);
        elename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        updatebutt.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        updatebutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updatebutt.setText("UPDATE");
        updatebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttActionPerformed(evt);
            }
        });

        insertbutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertbutt.setText("INSERT");
        insertbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        exitbutt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitbutt.setText("EXIT");
        exitbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tnotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(ttxt)
                    .addComponent(ttype)
                    .addComponent(captxt)
                    .addComponent(eleid)
                    .addComponent(elename))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertbutt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatebutt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ttype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(captxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(eleid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(elename, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        transt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        transt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transformer_no", "Transformer", "Transformer_type", "Capacity", "Elec_board_id", "Elec_board_name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        transt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(58, 58, 58))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void ttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttxtActionPerformed

    private void updatebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttActionPerformed
     
                          // TODO add your handling code here:
         try{ 
            PreparedStatement ps;
            ps=tran.Getconnection().prepareStatement("update transformer_master set transformer=?,transformer_type=?,capacity=?,elec_board_id=?,elec_board_name=? where transformer_no=?");
            ps.setString(1,ttxt.getText());
            ps.setString(2,ttype.getText());
            ps.setString(3,captxt.getText());
            ps.setString(4,eleid.getText());
            ps.setString(5,elename.getText());
            ps.setString(6,tnotxt.getText());
        if (JOptionPane.showConfirmDialog (null,"Confirm Modification","modification",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            ps.executeUpdate();
         ref_data();
        tnotxt.setText("");
        ttxt.setText("");
        ttype.setText("");
        captxt.setText("");
        eleid.setText("");
        elename.setText("");
            JOptionPane.showMessageDialog(null, "Data Updated Successfully");
        }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Unable to update :" + e.getLocalizedMessage());
            }        
                                    
    }//GEN-LAST:event_updatebuttActionPerformed

    private void insertbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttActionPerformed
        // TODO add your handling code here:
       
        String transformer_no = tnotxt.getText();
        String transformer = ttxt.getText();
        String transformer_type= ttype.getText();
        String capacity = captxt.getText();
        String elec_board_id = eleid.getText();
        String elec_board_name = elename.getText();
        try {
            
            PreparedStatement ps = tran.Getconnection().prepareStatement("insert into transformer_master (transformer_no,transformer,transformer_type,capacity ,elec_board_id,elec_board_name) values (?,?,?,?,?,?)");
            ps.setString(1,transformer_no );
            ps.setString(2,transformer );
            ps.setString(3,transformer_type  );
            ps.setString(4,capacity );
            ps.setString(5,elec_board_id);
            ps.setString(6,elec_board_name);
            ps.executeUpdate ();
           JOptionPane.showMessageDialog (null, "Data Inserted Successfully");
        ref_data();
        tnotxt.setText("");
        ttxt.setText("");
        ttype.setText("");
        captxt.setText("");
        eleid.setText("");
        elename.setText("");
        }
        catch (Exception e){           
            JOptionPane.showMessageDialog (null, "Unable to insert data: " + e.getLocalizedMessage());
        }
       
    }//GEN-LAST:event_insertbuttActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
             String dsql  = "Delete from transformer_master where transformer_no = '" + tnotxt.getText() + "'" ;
        try {
            if (JOptionPane.showConfirmDialog(this, "Attention You are going to delete location information","Delete transformer details",JOptionPane.YES_NO_OPTION)== JOptionPane.OK_OPTION) {
            if (tnotxt.getText().length() !=0){
            transtmt.executeUpdate(dsql);
            ref_data();
        tnotxt.setText("");
        ttxt.setText("");
        ttype.setText("");
        captxt.setText("");
        eleid.setText("");
        elename.setText("");
            JOptionPane.showMessageDialog(this,"Record Deleted Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this,"Enter Id value to delete..");
    
                 }    
              }
        }
        catch (Exception e) { 
           JOptionPane.showMessageDialog(this, "Unable to Delete:" + e.getLocalizedMessage());
        } 
    }//GEN-LAST:event_jButton4ActionPerformed
    private JFrame frame;
    private void exitbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttActionPerformed
        // TODO add your handling code here:
          frame=new JFrame("exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm to exit","elebill_system",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setVisible(false);
        }
    }//GEN-LAST:event_exitbuttActionPerformed
public void movedata (int i){
        try{
              tnotxt.setText(model.getValueAt(i, 0).toString());
              ttxt.setText(model.getValueAt(i ,1).toString());
              ttype.setText(model.getValueAt(i ,2).toString());
              captxt.setText(model.getValueAt(i ,3).toString());
              eleid.setText(model.getValueAt(i ,4).toString());   
              elename.setText(model.getValueAt(i ,5).toString());
        }
        catch (Exception e){
    System.err.println(e);
        JOptionPane.showMessageDialog(null,"Error in moving" + e.getLocalizedMessage());
    }
}
    private void transtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transtMouseClicked
        // TODO add your handling code here:
      try{
        int i=this.transt.getSelectedRow();
        movedata(i);
    } 
    catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error moving Data" + e.getLocalizedMessage());
    }
    }//GEN-LAST:event_transtMouseClicked

    private void eleidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eleidKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           disp_board_details(); 
        }
    }                                 
 
    
   private void disp_board_details() {
       String ele =eleid.getText();
       try
       {
           PreparedStatement ps =tran.Getconnection().prepareStatement("select elec_board_name " + " from electricity_board_master where elec_board_id=?");
           ps.setString(1,ele);
           tranrst=ps.executeQuery();
           if(tranrst.next() ){
              elename.setText(tranrst.getString("elec_board_name"));
              
         }
       }
           catch(Exception ex){
                 
                   Logger.getLogger(Consumer_entry.class.getName()).log(Level.SEVERE, null, ex);
                   }
       
      
        
    }//GEN-LAST:event_eleidKeyPressed
  private void ref_data() {
     try {
        model.setRowCount(0);
        tranrst = transtmt.executeQuery("select * from transformer_master");
        while(tranrst.next ()) {
        model.addRow(new Object[]
        {tranrst.getString("transformer_no"),tranrst.getString("transformer"),tranrst.getString("transformer_type"),tranrst.getString("capacity"),tranrst.getString("elec_board_id"),tranrst.getString("elec_board_name")});
         }
        }
         catch (Exception e){
             System.err.println(e);
         }
}      
    
           
          /*
          * @param args the command line arguments
       */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transformer_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transformer_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transformer_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transformer_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transformer_entry().setVisible(true);
            }
        });
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField captxt;
    private javax.swing.JTextField eleid;
    private javax.swing.JTextField elename;
    private javax.swing.JButton exitbutt;
    private javax.swing.JButton insertbutt;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tnotxt;
    private javax.swing.JTable transt;
    private javax.swing.JTextField ttxt;
    private javax.swing.JTextField ttype;
    private javax.swing.JButton updatebutt;
    // End of variables declaration//GEN-END:variables

}